try:
    with open("fname", "x") as fout:
        print("Archivo creado con Ã©xito")
except FileExistsError:
    print("El archivo ya existe")